name: 'techjavelin/iac-github-actions // terraform // prepare'
decsription: 'Creates a plan and makes it accessible as outputs and as a binary artifact to be consumed by apply'

inputs:
  source-dir:
    description: "Absolute path or relative path from project root to where your terraform files are"
    required: false
    default: '.'
  artifact-name:
    description: "Customize the name of the artifact" 
    required: false
    default: 'plan-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}'

outputs:
  plan: 
    description: "The plan output"
    value: ${{ steps.plan.outputs.stdout }}
  result:
    description: "The outcome of running plan"
    value: ${{ steps.plan.outcome }}
  artifact:
    description: "The name of the artifact uploaded"
    value: ${{ inputs.artifact-name }}

runs:
  using: composite
  steps:
    - name: terraform // prepare // setup
      uses: hashicorp/setup-terraform@v2

    - name: terraform // prepare // init
      id: init
      run: terraform -chdir=${{ inputs.source-dir }} init
      shell: bash

    - name: terraform // prepare // plan
      id: plan
      run: terraform -chdir=${{ inputs.source-dir }} plan -out=plan.tfplan -no-color
      shell: bash
    
    - name: terraform // prepare // upload        
      uses: actions/upload-artifact@v3
      id: upload
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.source-dir }}/plan.tfplan
        if-no-files-found: error
