---
name: Continuous Build

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    strategy:
      matrix:
        runner: [ 'ubuntu-latest' ]
        backend: [ 'local', 'terraform-cloud' ]
        test: [ 'simple' ]
        test-target: [ 'validate' ]
    
    uses: ./.github/workflows/test.yml
    with:
      test-name: ${{matrix.test}}
      backend-driver: ${{matrix.backend}}
