---
name: Continuous Build

on:
  push:
    branches:
      - 'main'

jobs:
  terraform-validate:
    strategy:
      matrix:
        runner: [ 'ubuntu-latest' ]
        backend: [ 'local', 'terraform-cloud' ]
        test: [ 'simple' ]
    uses: ./.github/workflows/iac-github-actions-test-terraform-workflows.yml
    with:
      test-path: ${{ runner.temp }}/workflow-terraform-${{matrix.test-target}}
