---
name: Continuous Build

on:
  push:
    branches:
      - 'main'

jobs:
  terraform-validate:
    strategy:
      matrix:
        test: [ 'simple' ]
        backend: [ 'local', 'terraform-cloud' ]
    uses: ./.github/workflows/iac-github-actions-test-terraform-workflows.yml
    with:
      test: ${{ matrix.test }}
      backend: ${{ matrix.backend }}
