---
name: Continuous Build

on:
  push:
    branches:
      - 'main'

jobs:
  terraform:
    strategy:
      matrix:
        test: [ 'simple' ]
        backend: [ 'local' ]
    uses: ./.github/workflows/iac-github-actions-test-terraform-workflows.yml
    with:
      test-name: ${{ matrix.test }}
      backend-driver: ${{ matrix.backend }}
