---
name: Continuous Build

on:
  push:
    branches:
      - 'main'

jobs:
  terraform-test:

  terraform-validate:
    strategy:
      matrix:
        runner: [ 'ubuntu-latest' ]
        backend: [ 'local', 'terraform-cloud' ]
        test: [ 'simple' ]
    uses: ${{ github.repository }}.github/workflows/iac-github-actions-test-terraform-workflows.yml@${{ github.sha }}
    with:
      test-path: workflow-terraform-${{matrix.test-target}}
