---
name: iac-github-actions // run-tests

on: 
  workflow_call:
    inputs:
      test-name:
        description: "Which tests to run"
        required: true
        type: string
      backend-driver:
        description: "The backend driver to use for the tests"
        required: true
        type: string

jobs:
  test:
    name: iac-github-actions // run-tests 
    needs: _run-tests
    runs-on: ubuntu-latest
    steps:
      - run: echo 

  _prepare-tests:
    strategy:
      fail-fast: true
      matrix: 
        target: [ 'workflow-terraform-validate', 'workflow-terraform-tflint' , 'workflow-terraform-prepare' ]
    uses: ./.github/workflows/prepare-tests.yml
    with:
      test-name: ${{ inputs.test-name }}
      backend-driver: ${{ inputs.backend-driver }}
      target: ${{ inputs.target }}

  _run-tests:
    needs: _prepare-tests
    strategy:
      fail-fast: true
      matrix: 
        target: [ 'workflow-terraform-validate', 'workflow-terraform-tflint' , 'workflow-terraform-prepare' ]
    uses: ./.github/workflows/run-tests.yml
    with:
      test-name: ${{ inputs.test-name }}
      backend-driver: ${{ inputs.backend-driver }}
      target: ${{ inputs.target }}
