---
name: iac-github-actions // run-tests

on: 
  workflow_call:
    inputs:
      test-name:
        description: "Which tests to run"
        required: true
        type: string
      backend-driver:
        description: "The backend driver to use for the tests"
        required: true
        type: string

jobs:
  test:
    name: iac-github-actions // run-tests 

    runs-on: ubuntu-latest

    env:
      test-path: ${{ inputs.test-name }}-${{ inputs.backend-driver }}-${{ github.run_id }}.${{ github.rub_number }}-${{ github.run_attempt }}

    steps:
      - name: iac-github-actions // run-tests // checkout
        uses: actions/checkout@v3

      - name: iac-github-actions // run-tests // prepare
        uses: ./.github/actions/prepare-tests
        with:
          test-name: ${{ inputs.test-name }}
          backend-driver: ${{ inputs.backend-driver }}
          tests-path: ${{ env.test-path }}

      - name: iac-github-actions // run-tests // validate
        uses: ./.github/actions/terraform-validate
        with:
          runner: ubuntu-latest
          source-dir: ${{ env.test-path }}
