---
name: iac-github-actions // run-tests

on: 
  workflow_call:
    inputs:
      test-name:
        description: "Which tests to run"
        required: true
        type: string
      backend-driver:
        description: "The backend driver to use for the tests"
        required: true
        type: string

jobs:
  test:
    name: iac-github-actions // run-tests 

    runs-on: ubuntu-latest

    env:
      test-path: ${{ inputs.test-name }}-${{ inputs.backend-driver }}-${{ github.run_id }}.${{ github.run_number }}-${{ github.run_attempt }}

    steps:
      - name: iac-github-actions // run-tests // checkout
        uses: actions/checkout@v3

      - name: iac-github-actions // run-tests // prepare
        uses: ./.github/actions/prepare-tests
        with:
          test-name: ${{ inputs.test-name }}
          backend-driver: ${{ inputs.backend-driver }}
          tests-path: ${{ env.test-path }}

      - name: iac-github-actions // run-tests // validate
        uses: ./.github/actions/terraform-validate
        with:
          source-dir: ${{ env.test-path }}

      - name: iac-github-actions // run-tests // lint
        uses: ./.github/actions/terraform-lint
        with:
          source-dir: ${{ env.test-path }}
        continue-on-error: true

      - name: iac-github-actions // run-tests // prepare
        id: prepare
        uses: ./.github/actions/terraform-prepare
        with:
          source-dir: ${{ env.test-path }}

      - run: |
          echo "Plan Outcome : ${{ steps.prepare.outcome }}"
          echo "Artifact     : ${{ steps.prepare.outputs.artifact }}"
          echo "::group::Plan"
          echo "Plan         : ${{ steps.prepare.outputs.plan }}"
          echo "::endgroup::"
