---
name: iac-github-actions // run-tests

on: 
  workflow_call:
    inputs:
      test-name:
        description: "Which tests to run"
        required: true
        type: string
      backend-driver:
        description: "The backend driver to use for the tests"
        required: true
        type: string

jobs:
  do-test-validate:
    needs: [ _prepare-tests ]
    uses: ./.github/workflows/workflow-terraform-validate.yml
    with:
      source_dir: test-${github.sha}
      runner: ubuntu-latest
      cache-dir: test-${{github.sha}}/
      cache-key: ${{github.sha}}

  _prepare-tests:
    runs-on: ubuntu-latest

    env:
      TEST_NAME: "${{ inputs.test-name }}"
      BACKEND: ${{ inputs.backend-driver }}

    steps:
      - name: iac-github-actions // test // checkout
        uses: actions/checkout@v3

      - name: iac-github-actions // test // terraform // cache
        uses: actions/cache@v3
        with:
          path: test-${{github.sha}}/
          key: ${{github.sha}}

      - name: iac-github-actions // test // terraform // prepare-tests
        id: prepare
        run: test/scripts/prepare_test.sh
        env:
          TEST_TARGET_PATH: test-${{github.sha}}/
