---
name: iac-github-actions // run-tests

on: 
  workflow_call:
    inputs:
      test-name:
        description: "Which tests to run"
        required: true
        type: string
      backend-driver:
        description: "The backend driver to use for the tests"
        required: true
        type: string
      target: 
        description: "The workflow being targeted"
        required: true
        type: string

jobs:
  test:
    name: iac-github-actions // run-tests 
    needs: _prepare-tests

    runs-on: ubuntu-latest

    steps:
      - name: iac-github-actions // run-tests // prespare
        uses: ./.github/actions/prepare-tests
        with:
          test-name: ${{ inputs.test-name }}
          backend-driver: ${{ inputs.backend-driver }}
          target: ${{ inputs.target }}

      - name: iac-github-actions // run-tests // validate
        uses: ./.github/actions/terraform-validate
        with:
          runner: ubuntu-latest
          source-dir: test
          cache-key: ${{github.sha}}-${{inputs.backend-driver}}-${{inputs.test-name}}-validate
        if: ${{ inputs.target == 'validate' }}

  # _prepare-tests:
  #   uses: ./.github/workflows/prepare-tests.yml
  #   with:
  #     test-name: ${{ inputs.test-name }}
  #     backend-driver: ${{ inputs.backend-driver }}
  #     target: ${{ inputs.target }}

  # _run-tests:
  #   needs: _prepare-tests
  #   strategy:
  #     fail-fast: true
  #     matrix: 
  #       target: [ 'workflow-terraform-validate', 'workflow-terraform-tflint' , 'workflow-terraform-prepare' ]
  #   uses: ./.github/workflows/run-tests.yml
  #   with:
  #     test-name: ${{ inputs.test-name }}
  #     backend-driver: ${{ inputs.backend-driver }}
  #     target: ${{ inputs.target }}
