---
name: iac-github-actions // run-tests

on: 
  workflow_call:
    inputs:
      test-name:
        description: "Which tests to run"
        required: true
        type: string
      backend-driver:
        description: "The backend driver to use for the tests"
        required: true
        type: string

env:
  test-path: ${{ inputs.test-name }}-${{ inputs.backend-driver }}-${{ github.run_id }}.${{ github.run_number }}-${{ github.run_attempt }}

jobs:
  prepare-tests:
    runs-on: ubuntu-latest
    steps:
      - name: iac-github-actions // run-tests // checkout
        uses: actions/checkout@v3

      - name: iac-github-actions // run-tests // prepare // cache-workspace
        id: cache-workspace
        uses: actions/cache@v3
        with:
          path: ${{ env.test-path }}
          key: ${{ env.test-path }}

      - name: iac-github-actions // run-tests // prepare
        uses: ./.github/actions/prepare-tests
        with:
          test-name: ${{ inputs.test-name }}
          backend-driver: ${{ inputs.backend-driver }}
          tests-path: ${{ env.test-path }}

  test-validation-no-errors:
    name: iac-github-actions // run-tests // test-validation-no-errors
    needs: prepare-tests
    runs-on: ubuntu-latest

    steps:
      - name: iac-github-actions // run-tests // test-validation // run-validate-action
        uses: ./.github/actions/terraform-validate
        with:
          source-dir: ${{ env.test-path }}

      - name: iac-github-actions // run-tests // test-validation // run-lint-action
        uses: ./.github/actions/terraform-lint
        with:
          source-dir: ${{ env.test-path }}
        continue-on-error: true

  test-prepare-no-errors:
    name: iac-github-actions // run-tests // test-prepare-no-errors
    needs: prepare-tests
    runs-on: ubuntu-latest

    steps:
      - name: iac-github-actions // run-tests // test-prepare-no-errors // run-prepare-action
        id: prepare
        uses: ./.github/actions/terraform-prepare
        with:
          source-dir: ${{ env.test-path }}

      - run: |
          echo "Plan Outcome : ${{ steps.prepare.outcome }}"
          echo "Artifact     : ${{ steps.prepare.outputs.artifact }}"
          echo "::group::Plan"
          echo "Plan         : ${{ steps.prepare.outputs.plan }}"
          echo "::endgroup::"

      - name: iac-github-actions // run-tests // test-prepare-no-errors // validate outcome
        uses: pr-mpt/actions-assert@v4
        with:
          assertion: npm://@assertions/is-equal:v1
          actual: ${{ steps.prepare.outputs.result }}
          expected: success

      - name: iac-github-actions // run-tests // test-prepare-no-errors // validate artifact
        uses: pr-mpt/actions-assert@v4
        with:
          assertion: npm://@assertions/is-equal:v1
          actual: ${{ steps.prepare.outputs.artifact }}
          expected: plan-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}

      