---
name: techjavelin/iac-github-actions // terraform // validate

on:
  workflow_call:
    inputs:
      runner:
        description: "Where the job should run (e.g. 'self-hosted', 'ubuntu-latest', etc)"
        required: true
        type: string
        default: 'ubuntu-latest'

      source-dir:
        description: "Absolute path or relative path from project root to where your terraform files are"
        required: false
        type: string
        default: '.'

      cache-key:
        description: "Will use a cached version of the source-dir if found"
        required: false
        type: string

    outputs:
      init:
        description: "Initialization Output"
        value: ${{ jobs.plan.outputs.init }}

      format:
        description: "Formatting Results"
        value: ${{ jobs.validate.outputs.outcome }}

      format_files:
        description: "Files formatted"
        value: ${{ jobs.validate.outputs.details }}

      validate:
        description: "Validation Results"
        value: ${{ jobs.validate.outputs.validation }}

jobs:
  lint:
    name: terraform // lint
    runs-on: ${{ inputs.runner }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ${{ inputs.source-dir }}
          key: ${{ inputs.cache-key }}
        if: ${{ inputs.cache-key != '' }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2
        with:
          tflint_version: v0.38.1

      - name: Initialize TFLint
        run: tflint --init
        working-directory: ${{ inputs.source-dir }}

      - name: Lint Terraform
        run: tflint -f compact
        working-directory: ${{ inputs.source-dir }}
