---
name: 'techjavelin/iac-github-actions // terraform // validate'
decsription: 'Performs a Validation of all terraform files'

inputs:
  runner:
    description: "Where the job should run (e.g. 'self-hosted', 'ubuntu-latest', etc)"
    required: true
    default: 'ubuntu-latest'

  source-dir:
    description: "Absolute path or relative path from project root to where your terraform files are"
    required: false
    default: '.'

  cache-key:
    description: "Will use a cached version of the source-dir if found"
    required: false

outputs:
  init:
    description: "Initialization Output"
    value: ${{ steps.init.outputs.init }}

  format:
    description: "Formatting Results"
    value: ${{ steps.format.outputs.outcome }}

  format_files:
    description: "Files formatted"
    value: ${{ steps.validate.outputs.details }}

  validate:
    description: "Validation Results"
    value: ${{ steps.validate.outputs.validation }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: ${{ inputs.source-dir }}
        key: ${{ inputs.cache-key }}
      if: ${{ inputs.cache-key != '' }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Setup
      id: init
      run: terraform -chdir=${{ inputs.source-dir }} init -backend=false
      shell: bash

    - name: Format
      id: format
      run: terraform -chdir=${{ inputs.source-dir }} fmt -no-color -recursive
      shell: bash

    - name: Validate
      id: validate
      run: terraform -chdir=${{ inputs.source-dir }} validate -no-color
      shell: bash
